export type ArtefactsItem = {
  id: string;
  name: string;
  code: string;
  year: string;
  image: string;
  images: string[];
  description: string;
  tags: string[];
};

export const artefactsItems: readonly ArtefactsItem[] = [
  {
    id: "kail-das",
    name: "kail das",
    code: "CH — 02A",
    year: "२०२५",
    image: "/bg-texture.jpeg",
    images: ["/bg-texture.jpeg"],
    description:
      "Kail Das is the first chair in the Das series. The chair is organised around a triptych seat and back panel. These three-part planes form the primary surfaces in contact with the body, while the legs and armature are assembled as standard members around them.\n\nAcross the series, this construction logic remains constant. Variation occurs through surface treatment, arm configuration and back height.\n\nKail Das retains the natural tone of Kail, Himalayan Blue Pine, and is configured with a single arm. Assembly relies predominantly on visible nailed joinery.",
    tags: ["Furniture", "Woodwork"],
  },
  {
    id: "alta-das",
    name: "alta das",
    code: "CH — 02B",
    year: "२०२५",
    image: "/bg-texture.jpeg",
    images: ["/bg-texture.jpeg"],
    description: "",
    tags: ["Furniture", "Woodwork"],
  },
  {
    id: "neel-das",
    name: "neel das",
    code: "CH — 02C",
    year: "२०२५",
    image: "/bg-texture.jpeg",
    images: ["/bg-texture.jpeg"],
    description: "",
    tags: ["Furniture", "Woodwork"],
  },
  {
    id: "nani-mahjong",
    name: "nani mahjong",
    code: "GM — 01A",
    year: "२०२५",
    image: "/bg-texture.jpeg",
    images: ["/bg-texture.jpeg"],
    description: "",
    tags: ["Games"],
  },
  {
    id: "sit-amet",
    name: "sit amet",
    code: "LR — 01A",
    year: "२०२५",
    image: "/bg-texture.jpeg",
    images: ["/bg-texture.jpeg"],
    description: "",
    tags: [],
  },
  {
    id: "faucibus-ex",
    name: "faucibus ex",
    code: "LR — 02A",
    year: "२०२५",
    image: "/bg-texture.jpeg",
    images: ["/bg-texture.jpeg"],
    description: "",
    tags: [],
  },
  {
    id: "adipiscing",
    name: "adipiscing",
    code: "LR — 03A",
    year: "२०२५",
    image: "/bg-texture.jpeg",
    images: ["/bg-texture.jpeg"],
    description: "",
    tags: [],
  },
  {
    id: "vitae-pellentesque",
    name: "vitae pellentesque",
    code: "LR — 04A",
    year: "२०२५",
    image: "/bg-texture.jpeg",
    images: ["/bg-texture.jpeg"],
    description: "",
    tags: [],
  },
  {
    id: "quisque",
    name: "quisque",
    code: "LR — 05A",
    year: "२०२५",
    image: "/bg-texture.jpeg",
    images: ["/bg-texture.jpeg"],
    description: "",
    tags: [],
  },
  {
    id: "sapien-elit",
    name: "sapien elit",
    code: "LR — 06A",
    year: "२०२५",
    image: "/bg-texture.jpeg",
    images: ["/bg-texture.jpeg"],
    description: "",
    tags: [],
  },
  {
    id: "das",
    name: "das",
    code: "LR — 07A",
    year: "२०२५",
    image: "/bg-texture.jpeg",
    images: ["/bg-texture.jpeg"],
    description: "",
    tags: [],
  },
  {
    id: "lorem-ipsum",
    name: "lorem ipsum",
    code: "LR — 08A",
    year: "२०२५",
    image: "/bg-texture.jpeg",
    images: ["/bg-texture.jpeg"],
    description: "",
    tags: [],
  },
  {
    id: "consectetur-am",
    name: "consectetur am",
    code: "LR — 09A",
    year: "२०२५",
    image: "/bg-texture.jpeg",
    images: ["/bg-texture.jpeg"],
    description: "",
    tags: [],
  },
  {
    id: "sit-amet-2",
    name: "sit amet",
    code: "LR — 10A",
    year: "२०२५",
    image: "/bg-texture.jpeg",
    images: ["/bg-texture.jpeg"],
    description: "",
    tags: [],
  },
  {
    id: "faucibus-ex-2",
    name: "faucibus ex",
    code: "LR — 11A",
    year: "२०२५",
    image: "/bg-texture.jpeg",
    images: ["/bg-texture.jpeg"],
    description: "",
    tags: [],
  },
  {
    id: "adipiscing-2",
    name: "adipiscing",
    code: "LR — 12A",
    year: "२०२५",
    image: "/bg-texture.jpeg",
    images: ["/bg-texture.jpeg"],
    description: "",
    tags: [],
  },
  {
    id: "vitae-pellentesque-2",
    name: "vitae pellentesque",
    code: "LR — 13A",
    year: "२०२५",
    image: "/bg-texture.jpeg",
    images: ["/bg-texture.jpeg"],
    description: "",
    tags: [],
  },
  {
    id: "quisque-2",
    name: "quisque",
    code: "LR — 14A",
    year: "२०२५",
    image: "/bg-texture.jpeg",
    images: ["/bg-texture.jpeg"],
    description: "",
    tags: [],
  },
  {
    id: "sapien-elit-2",
    name: "sapien elit",
    code: "LR — 15A",
    year: "२०२५",
    image: "/bg-texture.jpeg",
    images: ["/bg-texture.jpeg"],
    description: "",
    tags: [],
  },
];
