export const logs = [
  {
    name: "rabochi chairs",
    title: "TITLE",
    subtitle: "LOG X",
    creator: "Mannat Singh",
    date: "२०२५",
    descriptionTitle: "medium",
    description: `Proident cupidatat ad enim adipisicing nulla. Ex mollit duis deserunt sit excepteur qui et eu sint et aute id id consectetur. Lorem id fugiat tempor enim laboris. Do dolor voluptate dolore tempor reprehenderit aute excepteur fugiat laborum elit sunt excepteur. Lorem consectetur ullamco dolore et incididunt.`,
    tags: ["chair", "wood", "design"],
  },
  {
    name: "kangra studies I",
    title: "TITLE",
    subtitle: "LOG X",
    creator: "Mannat Singh",
    date: "२०२५",
    descriptionTitle: "medium",
    description: `Proident cupidatat ad enim adipisicing nulla. Ex mollit duis deserunt sit excepteur qui et eu sint et aute id id consectetur. Lorem id fugiat tempor enim laboris. Do dolor voluptate dolore tempor reprehenderit aute excepteur fugiat laborum elit sunt excepteur. Lorem consectetur ullamco dolore et incididunt.`,
    tags: ["chair", "wood", "design"],
  },
  {
    name: "bani ki tijori",
    title: "TITLE",
    subtitle: "LOG X",
    creator: "Mannat Singh",
    date: "२०२५",
    descriptionTitle: "medium",
    description: `Proident cupidatat ad enim adipisicing nulla. Ex mollit duis deserunt sit excepteur qui et eu sint et aute id id consectetur. Lorem id fugiat tempor enim laboris. Do dolor voluptate dolore tempor reprehenderit aute excepteur fugiat laborum elit sunt excepteur. Lorem consectetur ullamco dolore et incididunt.`,
    tags: ["chair", "wood", "design"],
  },
  {
    name: "dbh",
    title: "TITLE",
    subtitle: "LOG X",
    creator: "Mannat Singh",
    date: "२०२५",
    descriptionTitle: "medium",
    description: `Proident cupidatat ad enim adipisicing nulla. Ex mollit duis deserunt sit excepteur qui et eu sint et aute id id consectetur. Lorem id fugiat tempor enim laboris. Do dolor voluptate dolore tempor reprehenderit aute excepteur fugiat laborum elit sunt excepteur. Lorem consectetur ullamco dolore et incididunt.`,
    tags: ["chair", "wood", "design"],
  },
  {
    name: "czb",
    title: "TITLE",
    subtitle: "LOG X",
    creator: "Mannat Singh",
    date: "२०२५",
    descriptionTitle: "medium",
    description: `Proident cupidatat ad enim adipisicing nulla. Ex mollit duis deserunt sit excepteur qui et eu sint et aute id id consectetur. Lorem id fugiat tempor enim laboris. Do dolor voluptate dolore tempor reprehenderit aute excepteur fugiat laborum elit sunt excepteur. Lorem consectetur ullamco dolore et incididunt.`,
    tags: ["chair", "wood", "design"],
  },
];
